name: Kernel Build

on:
  workflow_dispatch:
  push:
    branches: [ floppy-new ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

- name: Clone AOSP Clang from googlesource (⚠️ Slow & Heavy)
  run: |
    git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang
    echo "CLANG_PATH=$(pwd)/clang/clang-r522817" >> $GITHUB_ENV

    - name: Set executable permission for build script
      run: chmod +x do_build.sh

    - name: Run Kernel Build Script
      env:
        PATH: ${{ env.CLANG_PATH }}/bin:${{ env.PATH }}
        CC: clang
        CLANG_TRIPLE: aarch64-linux-gnu-
        CROSS_COMPILE: aarch64-linux-gnu-
      run: ./do_build.sh ginkgo

    - name: Upload output files (zImage, Image.gz-dtb, etc)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kernel-output
        path: |
          out/arch/arm64/boot/*
